inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "lib/tasks/**/*"
    - "db/schema.rb"
    - "bin/*"
    - "test/*"
    - "node_modules/**/*"
    - "config/initializers/**/*"
    - "public/**/*"
    - "storage/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "terraform/**/*"
    - "openapi/**/*"
  NewCops: enable
